export const SET_LOGIN_LOADING = 'LOGIN/LOADING';
export const SET_FORGOT_PASSWOD_LOADING = 'FORGOTPASSWORD/LOADING';
export const SET_RESET_TOKEN_CHECK_LOADING = 'RESETTOKENCHECK/LOADING';
export const SET_RESET_PASSWORD_LOADING = 'RESETPASSWORD/LOADING';
