export const SET_DATA_LOADING = 'GALLERY/LOADING';
export const SET_SUBMIT_LOADING = 'GALLERY/SUBMITLOADING';
export const SET_DATA = 'GALLERY/DATA';
export const SET_COUNT = 'GALLERY/COUNT';
export const SET_PAGINATION = 'GALLERY/PAGINATION';
export const SET_FILTER = 'GALLERY/FILTER';
export const SET_ORDER = 'GALLERY/ORDER';
